from sqlmodel import Session, select
from app import models, schemas
from app.security import get_password_hash

# --- User CRUD ---
def get_user_by_email(db: Session, email: str) -> models.User | None:
    statement = select(models.User).where(models.User.email == email)
    return db.exec(statement).first()

def create_user(db: Session, user: schemas.UserCreate) -> models.User:
    hashed_password = get_password_hash(user.password)
    db_user = models.User(
        email=user.email, 
        hashed_password=hashed_password,
        encrypted_master_key=user.encrypted_master_key,
        master_key_salt=user.master_key_salt,
        master_key_iv=user.master_key_iv
        )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user

# --- Folder CRUD ---
def create_folder(db: Session, folder: schemas.FolderCreate, user_id: int) -> models.Folder:
    # Map "root" string from frontend to actual None in DB
    parent_id = None if folder.parent_id == "root" else folder.parent_id

    if parent_id is not None:
        parent_folder = db.get(models.Folder, parent_id)
        if not parent_folder or parent_folder.owner_id != user_id:
            raise ValueError("Parent folder not found or access denied")

    db_folder = models.Folder(
        name=folder.name,
        parent_id=parent_id,
        owner_id=user_id,
    )
    db.add(db_folder)
    db.commit()
    db.refresh(db_folder)
    return db_folder

# --- File CRUD ---
def create_file_record(db: Session, file: schemas.FileCreate, user_id: int) -> models.File:
    folder_id = None if file.folder_id == "root" else file.folder_id

    if folder_id is not None:
        parent_folder = db.get(models.Folder, folder_id)
        if not parent_folder or parent_folder.owner_id != user_id:
            raise ValueError("Folder not found or access denied")

    # The file_id_str is automatically generated by the Model's default_factory
    db_file = models.File(
        stored_filename=file.stored_filename,
        encrypted_metadata=file.encrypted_metadata,
        metadata_iv=file.metadata_iv,
        file_iv=file.file_iv,
        file_salt=file.file_salt,
        folder_id=folder_id,
        owner_id=user_id
    )

    db.add(db_file)
    db.commit()
    db.refresh(db_file)
    return db_file

def get_file_by_id(db: Session, file_id: str, user_id: int) -> models.File | None:
    """
    Look up file by its UUID Primary Key.
    """
    statement = select(models.File).where(
        models.File.id == file_id, 
        models.File.owner_id == user_id
    )
    return db.exec(statement).first()

def get_items_by_folder(db: Session, user_id: int, folder_id: str):
    parent_id = None if folder_id == "root" else folder_id

    # Get subfolders
    folder_statement = select(models.Folder).where(
        models.Folder.owner_id == user_id,
        models.Folder.parent_id == parent_id
    )
    folders = db.exec(folder_statement).all()

    # Get files
    file_statement = select(models.File).where(
        models.File.owner_id == user_id,
        models.File.folder_id == parent_id
    )
    files = db.exec(file_statement).all()

    return {"folders": folders, "files": files}