# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cortex_pb2 as cortex__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cortex_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AIServiceStub(object):
    """1. Define the Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestFile = channel.unary_stream(
                '/AIService/IngestFile',
                request_serializer=cortex__pb2.IngestRequest.SerializeToString,
                response_deserializer=cortex__pb2.IngestStatus.FromString,
                _registered_method=True)
        self.ChatWithDocument = channel.unary_unary(
                '/AIService/ChatWithDocument',
                request_serializer=cortex__pb2.ChatRequest.SerializeToString,
                response_deserializer=cortex__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/AIService/DeleteFile',
                request_serializer=cortex__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=cortex__pb2.DeleteFileResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """1. Define the Service
    """

    def IngestFile(self, request, context):
        """Processes a document (PDF, Docx, etc.) into vectors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatWithDocument(self, request, context):
        """Queries the indexed documents for answers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Delete File from the Qdrant Vector Database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestFile': grpc.unary_stream_rpc_method_handler(
                    servicer.IngestFile,
                    request_deserializer=cortex__pb2.IngestRequest.FromString,
                    response_serializer=cortex__pb2.IngestStatus.SerializeToString,
            ),
            'ChatWithDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatWithDocument,
                    request_deserializer=cortex__pb2.ChatRequest.FromString,
                    response_serializer=cortex__pb2.ChatResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=cortex__pb2.DeleteFileRequest.FromString,
                    response_serializer=cortex__pb2.DeleteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """1. Define the Service
    """

    @staticmethod
    def IngestFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/AIService/IngestFile',
            cortex__pb2.IngestRequest.SerializeToString,
            cortex__pb2.IngestStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatWithDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AIService/ChatWithDocument',
            cortex__pb2.ChatRequest.SerializeToString,
            cortex__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AIService/DeleteFile',
            cortex__pb2.DeleteFileRequest.SerializeToString,
            cortex__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
